### PR TITLE
Non-functional changes for RVV

### PR DESCRIPTION
**Pull request by liweiwei90**
Remove redundant require_vm/require_vector in current RVV macros. and remove unnecessary argument alu from require_vector_notype.

### CODE REVIEW

**Review by aswaterman — CHANGES_REQUESTED** [review]
I would support merging the first three commits, but I don't think the last three commits are an improvement.

**Comment by liweiwei90** [comment]
The last three are to remove the duplicate require_vector.  However, it needs introduce require_vector to some macros explicitly instead of reusing it in previous macro. I think it's a trade-off.

**Comment by aswaterman** [comment]
Yeah, I understand the motivation.  I think static code duplication is worse than the redundant check (which compilers can optimize).

**Comment by liweiwei90** [comment]
OK. I'll drop them.

**Review by aswaterman — APPROVED** [review]

**Pull request merged**
