### PR TITLE
fix loop condition in decode_insn

### PR DESCRIPTION
**Pull request by liweiwei90**

### CODE REVIEW

**Comment by scottj97** [comment]
This needs more context..."fix" what? What was wrong with the previous code?

**Comment by scottj97** [comment]
It appears this might have been broken by 5b7cdbe1cf75112bd2a472b7490b15fa7078d798 but why haven't we seen any problems until now?

**Comment by aswaterman** [comment]
I did break this in 5b7cdbe1cf75112bd2a472b7490b15fa7078d798.

I can see how this bug could manifest if a DECLARE_OVERLAP_INSN that isn't currently `supported` makes its way into the opcode_hash.  Not exactly sure how to force it to happen, though.

But... isn't the simpler and cleaner solution just to not register instructions that aren't supported, rather than carrying around the `supported` flag?  This allows us to get rid of all `nullptr`s from this code, eliminating this check altogether.  I've prototyped this idea in #997.

**Comment by liweiwei90** [comment]
Sorry. This happens when a instruction loaded from extlib resue the encode from instructions in (unratified) standard extension which is not enabled by --isa.
By the way, the null check for desc.func in the loop seems not right or unnecessary.

**Comment by aswaterman** [comment]
Superseded by #997.  Thanks for raising the issue!

**Pull request closed without merging**
