### PR TITLE
Add --priv command-line option to set which privilege modes are available

### PR DESCRIPTION
**Pull request by aswaterman**
Valid options are `--priv=msu` (the default), `--priv=mu`, and `--priv=m`.

### CODE REVIEW

**Comment by aswaterman** [comment]
@chihminchao @khannaudit

**Comment by khannaudit** [comment]
Are we now hardwiring `mstatus.fs` to 0 for systems without S mode and without F/D extension?

**Comment by aswaterman** [comment]
Forgot about that one.  Fixed.

**Comment by chihminchao** [comment]
It looks good to me.

**Comment by aswaterman** [comment]
Thanks for the review.  I'll merge now, with the expectation that @khannaudit might find a bug or two along the way.  (There shouldn't be any regressions when the `--priv` flag isn't used.)

**Pull request merged**
