### PR TITLE
Priv virtual memory updates

### PR DESCRIPTION
**Pull request by daniellustig**
* Priv 1.12 requires page faults when the address translation process
reaches a PTE with any reserved bit set

* Svpbmt uses two PTE bits, but otherwise has no effect on Spike (since
Spike is sequentially consistent and does not model PMAs)

* Add Svinval instructions

Even though I updated riscv-opcodes separately, I merged the new
defines into riscv/encoding.h manually, because riscv-opcodes seems
to be a step ahead of riscv-isa-sim for a few vector opcodes, causing
conflicts when regenerating encoding.h...

If that gets fixed, and encoding.h gets regenerated automatically, I can
remove it from this PR to avoid conflicts.

### CODE REVIEW

**Comment by aswaterman** [comment]
Since the new inval instructions are implemented identically to their fence counterparts, how about we use either symbolic links or e.g. `#include "sfence_vma.h"` to reuse the code that implements the fence instructions?

**Comment by aswaterman** [comment]
The rest LGTM.

**Comment by daniellustig** [comment]
> Since the new inval instructions are implemented identically to their fence counterparts, how about we use either symbolic links or e.g. `#include "sfence_vma.h"` to reuse the code that implements the fence instructions?

Sure, will make that change.  Any preference on handling encoding.h?  (see also https://github.com/riscv/riscv-tests/issues/350)

**Comment by aswaterman** [comment]
@daniellustig I'm OK with either only importing the necessary changes or fully overwriting the file with the newest auto-generated one.  I guess the latter is slightly preferable to make sure we aren't drifting, but if doing it that way breaks the build for some reason, then doing it the way you're currently doing it is fine.

**Comment by daniellustig** [comment]
OK pushed an update with the includes.

There are encoding.h conflicts with some really recent vector updates to riscv-opcodes, so if you're happy with the current approach I'd say let's leave this encoding.h as is and avoid mixing those vector changes into this PR.  Whenever that's resolved, a new autogenerated encoding.h should work too.  Thanks!

**Comment by aswaterman** [comment]
Cool. Yeah, I think some vector instructions got renamed and Spike is on the old names.

**Pull request merged**
