### PR TITLE
plic initialization optimize

### PR DESCRIPTION
**Pull request by WadeGao**
- optimize `num_ids_word` init logic;
- init `max_prio` by initialization-list

### CODE REVIEW

**Comment by aswaterman** [comment]
I have some forthcoming changes that I believe will conflict with this PR and might render it unnecessary. We can leave this open until that’s decided.

**Comment by WadeGao** [comment]
> 

👌🏻

**Comment by aswaterman** [comment]
Once #1265 is merged, can you rebase this?

**Review by aswaterman — APPROVED** [review]
Actually, nevermind: I'll merge this and rebase #1265.

**Comment by WadeGao** [comment]
> Actually, nevermind: I'll merge this and rebase #1265.

just wake up in UTC +8, thank you for your review

**Pull request merged**
