### PR TITLE
Add Smdbltrp

### PR DESCRIPTION
**Pull request by ved-rivos**
Spec: https://github.com/riscv/riscv-double-trap
Tests: https://github.com/riscv-non-isa/riscv-arch-test/pull/438

### CODE REVIEW

**Comment by ved-rivos** [comment]
This PR has a encoding.h change which is not merged upstream in riscv-opcodes yet. I will refresh it once the riscv-opcodes PR https://github.com/riscv/riscv-opcodes/pull/257 gets merged.

**Comment by aswaterman** [comment]
I merged the riscv-opcodes PR using a merge commit. The SHA hash is still valid, so there is no need to refresh encoding.h.

Please squash the two commits into a single commit, though.

I’ll perform a code review next week.

**Review by aswaterman — APPROVED** [review]
I didn't think about this one too deeply, but it looks good to me based on a cursory review.  Thanks!

**Comment by aswaterman** [comment]
@ved-rivos please fix the new conflicts and rebase/squash, then ping me to merge it.

**Comment by ved-rivos** [comment]
@aswaterman thanks. The conflicts have been resolved.

**Comment by ved-rivos** [comment]
@aswaterman - ptal if further changes are needed.

**Comment by aswaterman** [comment]
@ved-rivos thanks for the ping; I must've missed your previous message.

**Pull request merged**
