### PR TITLE
Incorporate supported privilege levels into isa_parser_t

### PR DESCRIPTION
**Pull request by rswarbrick**
*This is another commit plucked from #938. It probably makes sense no matter what we think about the general direction of that PR*

These affect the "max_isa" value (now exposed as get_max_isa()) and
feel like they're similar to the other computations done in
isa_parser_t.

### CODE REVIEW

**Comment by aswaterman** [comment]
I'm not sure about this one, for two reasons:
- the priv string, as it currently exists, has nothing to do with ISA strings, so passing it to the isa_parser doesn't seem like proper factoring.
- this probably creates additional technical debt, because `--priv` is a bit of a hack that I imagine we will deprecate and remove once RVI defines ISA strings that have the capability of expressing what we're currently expressing with the combination `--isa` and `--priv`.

**Comment by rswarbrick** [comment]
Thanks for the reply. The reason I did it like this is that the `max_isa` property on the ISA parser is affected by the priv string. At the moment, the processor subclass updates the parent class `max_isa` to make that work, which rather blurs the boundaries between the two classes.

I *think* I still believe this refactoring is a good idea. After all, you say above that we're eventually going to fold the `--priv` functionality into the ISA itself (once RVI defines appropriate ISA strings): isn't that an argument that this is the right place for the temporary hack to live?

If you feel strongly that we shouldn't do it like this, another approach would be to use a getter interface on `processor_t` that does the override for us. (Something like a `processor_t::get_max_isa()`, which will have pre-computed the value based on the underlying ISA parser plus the priv string). Do you think that would be better?

**Comment by aswaterman** [comment]
Maybe we can solicit another opinion from @scottj97.

**Comment by scottj97** [comment]
> The reason I did it like this is that the `max_isa` property on the ISA parser is affected by the priv string. At the moment, the processor subclass updates the parent class `max_isa` to make that work, which rather blurs the boundaries between the two classes.

I like this PR for the above reason.

(Also I just noticed that `processor_t` inherits from `isa_parser_t`, which is rather smelly. It feels like `processor_t` should contain an instance of `isa_parser_t` instead. Prefer composition over inheritance.)

**Comment by rswarbrick** [comment]
>  (Also I just noticed that processor_t inherits from isa_parser_t, which is rather smelly. It feels like processor_t should contain an instance of isa_parser_t instead. Prefer composition over inheritance.)

See the next commit in #938 (which is what prompted this change in the first place) :-D

**Comment by rswarbrick** [comment]
@aswaterman: Are you happy to proceed with this? Or are there changes that you'd like?

**Comment by aswaterman** [comment]
It's fine with me.

**Pull request merged**
