### PR TITLE
rvk: Sign-extension for sha256 insns

### PR DESCRIPTION
**Pull request by marcfedorow**
See #682 or #685 -- k-ext insns have the same problem.
There are a few fixes -- I kindly ask to check all the not-RV64-only insns.

### CODE REVIEW

**Comment by aswaterman** [comment]
Has the spec been updated accordingly yet?

**Comment by marcfedorow** [comment]
> Has the spec been updated accordingly yet?

This it not an issue of the spec but of the spike itself.
Kindly ask you to check #682 for the clarification.
TL;DR: on RV32 spike compares the whole 64-bit register with no sign extension so if some instruction's output was not sign extended (i.e. zero extended) but another (let's say `li`'s) was, spike thinks that e.g. `0x00000000FFFFFFFF != 0xFFFFFFFFFFFFFFFF` while actually only 32 LSBs should be checked.
According to #682 we agreed that every insns's output should be sign-extended to avoid such type of errors.

**Comment by aswaterman** [comment]
Indeed. cc @ben-marshall

**Comment by ben-marshall** [comment]
Thanks for the ping about this. Sign extension of the 32-bit SHA/AES/SM3/4 instructions in the spec is on my todo list, pending any more feedback from the architecture review. Thanks @marcfedorow for catching this issue in Spike!

**Pull request merged**
