### PR TITLE
Conditionalize Smepmp extension (ePMP) support

### PR DESCRIPTION
**Pull request by YenHaoChen**
I want to conditionalize Smepmp extension (ePMP) support, which provides a more flexible ISA configuration. This PR includes two modifications. First, it includes Smepmp to the ISA string parser. Second, it adds verifiy_permissions() for mseccfg_csr_t, which checks the permission for the mseccfg.

### CODE REVIEW

**Comment by YenHaoChen** [comment]
@soberl How do you feel about this?

**Comment by soberl** [comment]
@YenHaoChen  Looks good for me. Just one question from my side, what's the order for enum value for EXT_SMEPMP? Is there any rules for that?

**Comment by YenHaoChen** [comment]
@soberl I don't know whether there are rules for the order for the enum of extensions. Since the EXT_SMEPMP starts with 'EXT_S,' I put it with other extensions that begin with 'EXT_S.'

**Comment by soberl** [comment]
@YenHaoChen  Thanks. Maybe there is no rules needed since it's just an internal status. For users, the config interface is the ISA string. I am file with that.

**Review by scottj97 — APPROVED** [review]
I don't know anything about ePMP but I assume if `mseccfg==0` then the behavior matches the old PMP?

**Comment by YenHaoChen** [comment]
@scottj97 Yes, if mseccfg==0, the behavior matches the old PMP. That's why the Smepmp spec suggests implementing the reset value of mseccfg to zero for backward compatibility.
@soberl Would you help confirm this?
image

**Comment by soberl** [comment]
> @scottj97 Yes, if mseccfg==0, the behavior matches the old PMP. That's why the Smepmp spec suggests implementing the reset value of mseccfg to zero for backward compatibility. @soberl Would you help confirm this? image

Yes, the behavior should keep same when mseccfg==0. New features are based on RLB, MMWP and MML bits of mseccfg.

**Review by aswaterman — APPROVED** [review]
LGTM.

**Pull request merged**
