### PR TITLE
WIP on allowing gdb to connect to spike

### PR DESCRIPTION
**Pull request by timsifive**
This code isn't done, but it is possible to use gdb to connect to spike to debug a program (inspect/modify variables/registers, step, halt, use software breakpoints). There are probably bugs and corner cases remaining to be implemented. At the very least it'd be nice to support more than one core. That said, I'd rather get code reviewed sooner than later. (Arguably I've waited too long already.)

Note that accessing CSR registers this code assumes [this pull request](https://github.com/riscv/riscv-binutils-gdb/pull/6) has been accepted to gdb. Debugging should work fine without this change as long as you don't access any CSRs.

Some other changes that crept in while I was working on this:
1. Treat compiler warnings as errors. The code is currently clean, and that's the best way to keep it that way.
2. Extend the 'make check' mechanism (which wasn't used in any case) to support scripts or other binaries besides C++ source.

### CODE REVIEW

**Comment by aswaterman** [comment]
this looks good to me so far.  should we wait to merge until it's done?

**Comment by timsifive** [comment]
I'd rather merge early if possible. That will prevent possible conflicts, let people use the functionality that's there so far, and also serve as an announcement that it's being worked on.

**Comment by aswaterman** [comment]
This will break EBREAK for not-debugging case.  Should I begin implementing the RISC-V debug module in Spike (namely, dcsr)?

**Comment by timsifive** [comment]
That would be a reasonable way of dealing with this.
A simpler short term solution is to only break EBREAK when gdb is actually connected. This will handle 99% of the use cases. I doubt that the finer control that dcsr provides will be used much.

**Comment by aswaterman** [comment]
Makes sense to me in short term -- in practice, I think this would only
break when using native gdb, as well.

**Comment by timsifive** [comment]
I'll implement this.

**Comment by timsifive** [comment]
Done. I don't know if you get notified when I add more commits, but I'm pretty sure you do when I comment.

**Comment by ccelio** [comment]
I can't speak for Andrew, but I only see notifications for new pull requests, issues, and comments on PRs and Issues. Any commits - to master or to PRs - are invisible.

**Comment by timsifive** [comment]
Can this code be merged? As I see it it adds some functionality that is already somewhat useful, and doesn't break anything. I prefer to much sooner rather than later.

**Comment by dvc94ch** [comment]
I tested this branch and ran into two unrelated issues with a RV64IMAFD and a RV32I toolchain.
With the RV64IMAFD toolchain:

```
[nix-shell:~/.nixpkgs/test]$ spike --gdb-port 9824 $(which pk) hello64
warning: only got 2934964224 bytes of target mem (wanted 4026531840)
../machine/configstring.c:45: assertion failed: num_harts

[nix-shell:~/.nixpkgs/test]$ spike -d $(which pk) hello64
warning: only got 2934964224 bytes of target mem (wanted 4026531840)
: 
core   0: 0x0000000000001000 (0x7ffff297) auipc   t0, 0x7ffff
: 
core   0: 0x0000000000001004 (0x00028067) jr      t0
: 
core   0: 0x0000000080000000 (0x1a80006f) j       pc + 0x1a8
: 
core   0: 0x00000000800001a8 (0x00000093) li      ra, 0
: 
core   0: 0x00000000800001ac (0x00000113) li      sp, 0
: 
core   0: 0x00000000800001b0 (0x00000193) li      gp, 0
: q

[nix-shell:~/.nixpkgs/test]$ cat hello.c
#include <stdio.h>

void main(void)
{
    printf("Hello world");
}
```

With RV32I toolchain:

```
[nix-shell:~/.nixpkgs/test]$ spike --gdb-port 9824 $(which pk) hello
warning: only got 2934964224 bytes of target mem (wanted 4026531840)
Received malformed 1-byte packet from debug client: +

[nix-shell:~/.nixpkgs]$ riscv32-unknown-elf-gdb
GNU gdb (GDB) 7.11.50.20160212-git
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "--host=x86_64-pc-linux-gnu --target=riscv32-unknown-elf".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word".
(gdb) target remote localhost:9824
Remote debugging using localhost:9824
0x40f03823 in ?? ()
(gdb) 
```

If it's helpful or someone is interested I can post git hashes and build instructions I used for the builds.

**Comment by timsifive** [comment]
On Sat, May 21, 2016 at 8:13 AM, David Craven notifications@github.com
wrote:

> I tested this branch and ran into two unrelated issues with a RV64IMAFD
> and a RV32I toolchain.
> With the RV64IMAFD toolchain:
> 
> [nix-shell:~/.nixpkgs/test]$ spike --gdb-port 9824 $(which pk) hello64
> warning: only got 2934964224 bytes of target mem (wanted 4026531840)
> ../machine/configstring.c:45: assertion failed: num_harts
> 
> This one is because my spike changes are based on a slightly old spike. I
> think I have that addressed locally. I just need to brush up on my git to
> figure out how to push the rebased code. Hopefully that will happen later
> today.
> 
> With RV32I toolchain:
> 
> I should have mentioned that the current debug support is only written
> for/tested with RV64. I know there are changes required to make it work
> with RV32. I should get to that in the coming weeks.

Tim

**Comment by timsifive** [comment]
On Sat, May 21, 2016 at 9:45 AM, Tim Newsome tim@sifive.com wrote:

> On Sat, May 21, 2016 at 8:13 AM, David Craven notifications@github.com
> wrote:
> 
> > I tested this branch and ran into two unrelated issues with a RV64IMAFD
> > and a RV32I toolchain.
> > With the RV64IMAFD toolchain:
> > 
> > [nix-shell:~/.nixpkgs/test]$ spike --gdb-port 9824 $(which pk) hello64
> > warning: only got 2934964224 bytes of target mem (wanted 4026531840)
> > ../machine/configstring.c:45: assertion failed: num_harts
> > 
> > This one is because my spike changes are based on a slightly old spike. I
> > think I have that addressed locally. I just need to brush up on my git to
> > figure out how to push the rebased code. Hopefully that will happen later
> > today.

I've force pushed a rebased master. My repo had turned into a bit of mess,
so this was necessary. Assuming you didn't make any local changes I think
'git pull' will just do the right thing, but you may have to clone a new
repo.

Tim

> With RV32I toolchain:
> 
> > I should have mentioned that the current debug support is only written
> > for/tested with RV64. I know there are changes required to make it work
> > with RV32. I should get to that in the coming weeks.
> 
> Tim

**Comment by dvc94ch** [comment]
Yes that fixed it! Thanks Tim.

**Comment by timsifive** [comment]
Great! Let me know how things work out.

Tim

**Pull request merged**
