### PR TITLE
Assert misa.B bit through --isa=...B...

### PR DESCRIPTION
**Pull request by YenHaoChen**
This PR provides misa.B=1 by --isa=...B...

Reference: https://github.com/riscv-software-src/riscv-isa-sim/pull/1559

### CODE REVIEW

**Review by aswaterman — CHANGES_REQUESTED** [review]
Seems like we are becoming inconsistent about how we handle these different cases, in multiple ways:

- For P, we use the [switch statement](https://github.com/riscv-software-src/riscv-isa-sim/blob/3192ee4d31f481e84281a24d55bb6130e3743668/disasm/isa_parser.cc#L73) to populate the Zp extensions, rather than the if statements at the bottom.  (This is only a stylistic concern; we don't need to fix it right now, but I thought it was worth mentioning.)
- For A, we make it so that A implies Zaamo and Zalrsc, but we don't make Zaamo + Zalrsc imply A.  This is inconsistent with what you propose we do for B.  We should either delete the logic that makes Zba + Zbb + Zbs imply B, or add the logic so that Zaamo + Zalrsc imply A.  I think people would prefer the latter option, so that `misa` will contain A if Zaamo+Zalrsc is specified.

**Comment by YenHaoChen** [comment]
Thank you. I was not aware of the inconsistency. I targeted the missing character 'b' in the variable 'all_subsets,' which supports --isa=...B...

Let's delete the logic that makes Zba + Zbb + Zbs imply B in this PR. I will provide another PR that discusses the implications of A and B.

**Comment by aswaterman** [comment]
Does this version still make B imply Zba+Zbb+Zbs? It isn’t clear to me how it works.

**Comment by YenHaoChen** [comment]
> Does this version still make B imply Zba+Zbb+Zbs? It isn’t clear to me how it works.

Yes, we have B implying Zba+Zbb+Zbs (disasm/isa_parser.cc:333). The previous PR (https://github.com/riscv-software-src/riscv-isa-sim/pull/1559) provided the code for implication, which aims at the B extension. Unfortunately, it does not offer --isa=...B... functionality from the optional flag. This PR catches up with the missing.

**Comment by aswaterman** [comment]
Ah, got it.

**Review by aswaterman — APPROVED** [review]

**Pull request merged**
