### PR TITLE
Build and install the lib and header dependencies required by Hammer

### PR DESCRIPTION
**Pull request by jerinjoy**
https://github.com/rivosinc/hammer

Signed-off-by: Jerin Joy <joy@rivosinc.com>

### CODE REVIEW

**Review by aswaterman — CHANGES_REQUESTED** [review]
It looks like we are currently using tabs, rather than spaces, in these Makefiles.  Maybe that was a questionable decision, but can you follow it for consistency?

Also, please add a trailing slash to the final items in these lists to reduce the diff when the lists are expanded.

**Comment by aswaterman** [comment]
Pleasantly surprised to see that `-fPIC` does not cause a performance regression.

**Comment by jerinjoy** [comment]
I've replaced the spaces with tabs and I've added the trailing slash.

**Comment by jerinjoy** [comment]
I accidentally pushed an empty commit and the PR got closed. Reopened with the requested changes.

**Review by aswaterman — APPROVED** [review]
Thank you!

**Pull request merged**
