### PR TITLE
[NFC] Simplify vmulhsu

### PR DESCRIPTION
**Pull request by eopXD**

### CODE REVIEW

**Comment by scottj97** [comment]
What does "[NFC]" mean?

**Comment by aswaterman** [comment]
I would also like to know the answer to that question, but in the mean time, I'm merging this.

**Comment by eopXD** [comment]
It stands for No Functional Changes :)

**Comment by scottj97** [comment]
I can see that this commit changes the behavior of `vmulhsu`!


Initial state:
```
v14=0xc31f28da53cb1a306277ad3af986ae8e
v15=0x4a88ed6ddc4015dd97000e11163b7695
vl=0x10
vtype=0
vstart=0
```
Commit log diff shows:
```
 core   0: 0x0000000080002390 (0x9ae7ad57) vmulhsu.vv v26, v14, v15
-core   0: 3 0x0000000080002390 (0x9ae7ad57) c8_vstart 0x0000000000000000 e8 m1 l16 v26 0xee1025ef47f202293900fb03ffe3dabd c768_mstatus 0x8000000a00006600
+core   0: 3 0x0000000080002390 (0x9ae7ad57) c8_vstart 0x0000000000000000 e8 m1 l16 v26 0xeef1fdeff4f202f9d700fb03ffe3da2f c768_mstatus 0x8000000a00006600
```

**Comment by aswaterman** [comment]
I see, the vs1 argument is being sign-extended before it's being zero-extended.  I'll revert this right now.  Not sure if there's a more elegant way to handle this that's also correct.

**Pull request merged**
