### PR TITLE
Return non-zero trap value for illegal CSR accessing instructions

### PR DESCRIPTION
**Pull request by IanJiangICT**
The original Spike always returns zero in mtval/stval for illegal instruction traps that accessing CSR.
Here another choice is provided that returns instruction bits rather zero.
A command line parameter --tval-nz-csr is also added to turn this function on.

### CODE REVIEW

**Review by aswaterman — COMMENTED** [review]
This patch doesn’t make sense to me. The illegal-instruction reporting feature doesn’t have anything to do with the csrrx instructions.

**Review by aswaterman — COMMENTED** [review]
This patch doesn’t make sense to me. The illegal-instruction reporting feature doesn’t have anything to do with the csrrx instructions.

**Comment by IanJiangICT** [comment]
> This patch doesn’t make sense to me. The illegal-instruction reporting feature doesn’t have anything to do with the csrrx instructions.

The RISC-V Instruction Set Manual Volume II: Privileged Architecture Document Version 1.12-draft
2.1 CSR Address Mapping Conventions
"Attempts to access a CSR without appropriate privilege level or to write a read-only register also raise illegal instruction
exceptions."

**Comment by aswaterman** [comment]
But you’re only enabling the feature for csrrx, not other instructions. A proper fix would orthogonally implement it for all illegal instructions, not only a tiny subset.

**Pull request closed without merging**
