### PR TITLE
fix typos

### PR DESCRIPTION
**Pull request by howjmay**

### CODE REVIEW

**Review by aswaterman — CHANGES_REQUESTED** [review]
`configure` is an auto-generated file; please don't modify it unless as a result of running `autoconf`.

`fdt` is a copy of an open-source library that is maintained elsewhere; we should not modify it here.

The other changes are OK.

**Comment by howjmay** [comment]
fixed. Thank you for review

**Review by aswaterman — APPROVED** [review]
Thanks.

**Comment by howjmay** [comment]
thank you too

**Pull request merged**
