### PR TITLE
Fix the relationship between Zce and Zcf

### PR DESCRIPTION
**Pull request by liweiwei90**
Zcf is RV32 only.

### CODE REVIEW

**Review by aswaterman — APPROVED** [review]

**Comment by scottj97** [comment]
Does [this line](https://github.com/riscv-software-src/riscv-isa-sim/blob/f29dcd0d34bfc8c7d8982c9d03dc2e40bbc2f212/riscv/csrs.cc#L638) need a corresponding change too?
```
  proc->set_extension_enable(EXT_ZCF, (new_misa & (1L << ('F' - 'A'))) && proc->extension_enabled(EXT_ZCA));
```

**Comment by aswaterman** [comment]
@scottj97 Turns out it's benign, because all code paths that check whether Zcf is enabled are gated by XLEN being 32.  But it might be better to keep this code in sync with the ISA parser, in case we later attempt to refactor and share the logic.

**Comment by scottj97** [comment]
> @scottj97 Turns out it's benign, because all code paths that check whether Zcf is enabled are gated by XLEN being 32. But it might be better to keep this code in sync with the ISA parser, in case we later attempt to refactor and share the logic.

Does that mean that [00066cb](https://github.com/riscv-software-src/riscv-isa-sim/pull/1285/commits/00066cb3655314f07f7b13f225d98e66d32bfd87) was also benign?

**Comment by aswaterman** [comment]
Yes, I hadn't thought that through when I approved it.  In any case, I think we should be consistent and add the check to `csrs.cc`, too.

**Pull request merged**
