### PR TITLE
vector: disassemble: Let operand ordering be vd, [vrf]s1, vs2 to vector multiply-add instructions

### PR DESCRIPTION
**Pull request by YenHaoChen**
Vector integer multiply-add instructions have a different assembly format to others. Specifically, the operand ordering of these instructions is rd, [vr]s1, vs2, while one of the others is rd, vs2, [vr]s1. (I was wondering whether this is a bug to the spec. Please correct me if I am wrong about this.)

image

### CODE REVIEW

**Review by aswaterman — APPROVED** [review]

**Review by aswaterman — CHANGES_REQUESTED** [review]
The spec is correct; see this NOTE: https://github.com/riscv/riscv-isa-manual/blob/8b9dc50e562af27c9ab22ae0a2d3bf528c6bd41d/src/v-st-ext.adoc#L2264-L2268

However, I think your fix is incomplete.  It includes only integer instructions.

You also need the single-width floating-point FMAs: https://github.com/riscv/riscv-isa-manual/blob/8b9dc50e562af27c9ab22ae0a2d3bf528c6bd41d/src/v-st-ext.adoc#L3331-L3362

And the widening floating-point FMAs: https://github.com/riscv/riscv-isa-manual/blob/8b9dc50e562af27c9ab22ae0a2d3bf528c6bd41d/src/v-st-ext.adoc#L3376-L3390

I believe that is all.

**Comment by YenHaoChen** [comment]
@aswaterman Thank you for the review. I revised the PR and made the following changes.
+ Breakdown the commit by instruction group from the debug spec, i.e., splitting https://github.com/riscv-software-src/riscv-isa-sim/commit/d3988721795567907f0e90e4d29a00aa1c791689 into https://github.com/riscv-software-src/riscv-isa-sim/pull/1797/commits/ff6210921127925582802bf7e7ad6952c0e0758f and https://github.com/riscv-software-src/riscv-isa-sim/pull/1797/commits/7f38a503d032adafc10b3e9eea006d65e464e991.
+ Let operand ordering be vd, [vf]s1, vs2 to vector floating-point fused multiply-add instructions, i.e., adding https://github.com/riscv-software-src/riscv-isa-sim/pull/1797/commits/b47d0baab34a03268f936c1c9400d61c46d54d67 and https://github.com/riscv-software-src/riscv-isa-sim/pull/1797/commits/6a1a5db16b60abaecd235f78f5d70716bf47c9a9.

**Review by aswaterman — APPROVED** [review]
LGTM now, thanks.

**Comment by aswaterman** [comment]
@YenHaoChen I sent you a github invite with write permissions so that you can directly participate in PR reviews (and so that you can merge your own PRs once they're approved).

**Comment by YenHaoChen** [comment]
@aswaterman Thank you.

**Pull request merged**
