### PR TITLE
Add `statx` syscall to Spike

### PR DESCRIPTION
**Pull request by huaixv**
The `statx` syscall is required to run some 32bit programs on Spike and `riscv-pk`, so i tried to add it to the simulator. :)

Please let me know if there exist some problems with the code.

### CODE REVIEW

**Comment by huaixv** [comment]
Just found that `stx_mnt_id` field in `struct statx` was introduced in linux v5.8, but Ubuntu 20.04 is using v5.4.
So I added another `AC_CHECK_MEMBER` call to check its existence, and it builds well.

**Comment by aswaterman** [comment]
LGTM.

**Comment by aswaterman** [comment]
Actually, it does not LGTM :) it fails to build on Ubuntu 16.04.

**Comment by aswaterman** [comment]
I added another configure check for the statx structure overall, which fixes the Ubuntu 16.04 build.  You should check that you're still getting expected results on newer OSes.

**Comment by huaixv** [comment]
Thank you for your response.
But the kernel header defines inode member as `stx_ino` instead of `ino`, so the configure script will not define `HAVE_STATX`. :(

**Comment by aswaterman** [comment]
OK, I pushed yet another fix.

**Pull request merged**
