### PR TITLE
Splitted K-ext to zeds

### PR DESCRIPTION
**Pull request by marcfedorow**

### CODE REVIEW

**Comment by aswaterman** [comment]
@ben-marshall please review

**Review by ben-marshall — APPROVED** [review]

**Comment by ben-marshall** [comment]
This was on my to-do list for next week so thank you very much @marcfedorow for getting in there first.

Everything looks as I'd expect. It means we can specify all of the individual extensions in the scalar crypto spec, rather than, as previously, just adding `K` to the ISA string.

**Comment by aswaterman** [comment]
Thanks.  I'm going to wait until #793 is merged before handling this one, because I've already caused @scottj97 enough pain.

**Comment by aswaterman** [comment]
OK, #793 has been merged; please rebase.

**Comment by marcfedorow** [comment]
@aswaterman Done

**Comment by marcfedorow** [comment]
@aswaterman, Should I do something else?

**Comment by aswaterman** [comment]
Nope, looks good now.  Thanks!

**Pull request merged**
