### PR TITLE
Correct c.li and c.lui disassembly

### PR DESCRIPTION
**Pull request by palmer-dabbelt**
I currently get this disassembly

    00004881 jr      a7

but I want

    00004881 li      a7, 0

### CODE REVIEW

**Review by colinschmidt — APPROVED** [review]
LGTM. Has it always been broken?

**Comment by aswaterman** [comment]
Yes, and there are probably some other broken ones.

**Comment by aswaterman** [comment]
Can you verify that C.MV and C.ADD still disassemble correctly?  (They're the ones that share the opcode with C.JR and C.JALR, when rs2 != 0.)  If so, feel free to merge.

**Comment by palmer-dabbelt** [comment]
@colinschmidt spike-dasm pretty much only gets called to disassemble Rocket commit logs, and until yesterday Rocket put the decompressed instructions into the commit log.  I doubt any of this has ever been tested.

@aswaterman 
````
   0:   4505                    c.li    a0,1
   2:   8502                    c.jr    a0
   4:   0505                    c.addi  a0,1
   6:   852e                    c.mv    a0,a1
   8:   952e                    c.add   a0,a1
````

````
00004505 li      a0, 1
00008502 jr      a0
00000505 addi    a0, a0, 1
0000852e mv      a0, a1
0000952e add     a0, a0, a1
````

**Pull request merged**
