### PR TITLE
Relax VLEN requirement to 65,536 bytes in processor module

### PR DESCRIPTION
**Pull request by luojia65**
Related issue: https://github.com/riscv-software-src/riscv-isa-sim/issues/1502

### CODE REVIEW

**Comment by sequencer** [comment]
> (after testing it thoroughly)

How did you test for it?

**Comment by luojia65** [comment]
I'm sorry that I don't have a test environment locally, it would be somehow hard to test. If there are more test cases other than CI, please note me and I'll try to run them locally. By now I'd wait before CI result.

**Comment by sequencer** [comment]
Basically the community has
https://github.com/ksco/riscv-vector-tests
For test case generation
You can run it to check there are no internal exceptions from spike.

Since for riscv community, spike is the golden model that doesn’t have a
diamond model which can be used for testing, neither do I have any idea to
verify the correctness.

However testing spike against t1 for cross reference(we already have a
corresponding test framework) is a possible solution, if you are willing
to, you can send PR to t1, and our engineers will help you debugging for
any mismatches on both spike and t1.

**Comment by aswaterman** [comment]
Yeah, I can’t accept this until I hear a more solid testing story.

**Pull request closed without merging**
