### PR TITLE
Add support for Svadu Extension

### PR DESCRIPTION
**Pull request by adurbin-rivos**
The Svadu (https://github.com/riscv/riscv-svadu) extension updates
the A/D bits of PTEs:

1. In S/HS mode when menvcfg.hade=1
2. In G-stage page tables when menvcfg.hade=1
3. In VS mode when henvcfg.hade=1

The --mmu-dirty flag and the dirty_enabled cfg state were removed. The
result is that Svadu extension needs to be enabled in the ISA string
as well as setting the HADE bits in menvcfg and henvcfg to obtain that
previous behavior.

### CODE REVIEW

**Comment by adurbin-rivos** [comment]
I have not tested this yet. Wanted to put this up for a quick look-see.

**Comment by scottj97** [comment]
Without even looking at it I’d say this needs to be broken up into many
separate commits. Such as:

1. Add parsing of new isa flag
2. Add new writable bits to CSRs (that have no effect yet)
3. Switch A/D behavior to use new bits instead of —mmu-dirty
4. Remove —mmu-dirty option
5. Remove dirty_enabled from cfg

When you put all these steps into one giant commit it becomes much harder
to understand, review, and regression test.

**Comment by aswaterman** [comment]
Agreed w/Scott.

**Comment by adurbin-rivos** [comment]
ok. I didn't know how the project normally likes the dev flow w.r.t. patches. I can break them up. I'll also check on the build failures. It was building on my end.

**Comment by scottj97** [comment]
Please fix typo (henvfg) in commit message for a4487886419ea8c8e04bdd408aa3411f70636e83

Thanks for splitting up. I'll be taking a closer look soon.

**Comment by adurbin-rivos** [comment]
> Please fix typo (henvfg) in commit message for [a448788](https://github.com/riscv-software-src/riscv-isa-sim/commit/a4487886419ea8c8e04bdd408aa3411f70636e83)
> 
> Thanks for splitting up. I'll be taking a closer look soon.

done

**Comment by scottj97** [comment]
It will help my regression testing if you can split 0e6269fafe30ebaf8cbfc51aa61d1f3259a18ad2 to first add the bits to the CSRs and then in the next commit, use those new bits to control the A/D.

**Comment by adurbin-rivos** [comment]
> It will help my regression testing if you can split [0e6269f](https://github.com/riscv-software-src/riscv-isa-sim/commit/0e6269fafe30ebaf8cbfc51aa61d1f3259a18ad2) to first add the bits to the CSRs and then in the next commit, use those new bits to control the A/D.

What are you doing for your regression testing? I'm curious because this sequence of patches (not the request above) neuters behavior which sort of breaks regression testing in general. I'm happy to split things more, but I don't see why adding CSR bits and then taking action on them helps.  I'm trying to understand the motivation and approach so it clicks in my head. Thanks in advance.

**Comment by scottj97** [comment]
> What are you doing for your regression testing? I'm curious because this sequence of patches (not the request above) neuters behavior which sort of breaks regression testing in general. I'm happy to split things more, but I don't see why adding CSR bits and then taking action on them helps. I'm trying to understand the motivation and approach so it clicks in my head. Thanks in advance.

I have a proprietary system that I developed with lots of company-internal tests.

By adding the CSR bits first I can observe and record that change in the commit logs, and easily verify that nothing else has changed. Then I can pull the next commit and verify zero behavior change (since I will be both using `--mmu-dirty` and setting `menvcfg.HADE=1`). Then I remove `--mmu-dirty` from my command lines and verify zero behavior change. Then I pull each of the remaining commits and verify zero behavior change on each.

By splitting things up I can take smaller steps and have higher confidence in the correctness of each step.

**Comment by adurbin-rivos** [comment]
> > What are you doing for your regression testing? I'm curious because this sequence of patches (not the request above) neuters behavior which sort of breaks regression testing in general. I'm happy to split things more, but I don't see why adding CSR bits and then taking action on them helps. I'm trying to understand the motivation and approach so it clicks in my head. Thanks in advance.
> 
> I have a proprietary system that I developed with lots of company-internal tests.
> 
> By adding the CSR bits first I can observe and record that change in the commit logs, and easily verify that nothing else has changed. Then I can pull the next commit and verify zero behavior change (since I will be both using `--mmu-dirty` and setting `menvcfg.HADE=1`). Then I remove `--mmu-dirty` and verify zero behavior change. Then I pull each of the remaining commits and verify zero behavior change on each.
> 
> By splitting things up I can take smaller steps and have higher confidence in the correctness of each step.

10-4. I was hoping I could leverage what you were doing as well. For the CSR bits, do you want me to take the pieces from  [0e6269f](https://github.com/riscv-software-src/riscv-isa-sim/commit/0e6269fafe30ebaf8cbfc51aa61d1f3259a18ad2) and put them into [5322213](https://github.com/riscv-software-src/riscv-isa-sim/pull/1240/commits/53222130f60b2d651970a23a60b4f3ab86731ba5)? Or standalone?

**Comment by scottj97** [comment]
> 10-4. I was hoping I could leverage what you were doing as well. For the CSR bits, do you want me to take the pieces from [0e6269f](https://github.com/riscv-software-src/riscv-isa-sim/commit/0e6269fafe30ebaf8cbfc51aa61d1f3259a18ad2) and put them into [5322213](https://github.com/riscv-software-src/riscv-isa-sim/pull/1240/commits/53222130f60b2d651970a23a60b4f3ab86731ba5)? Or standalone?

I wish I could share my system.

Standalone please. More commits is always better. Regeneration of `encoding.h` from the upstream source is good to have isolated.

**Comment by adurbin-rivos** [comment]
> Standalone please. More commits is always better. Regeneration of `encoding.h` from the upstream source is good to have isolated.

done

**Review by scottj97 — APPROVED** [review]
Thank you for the contribution. This is well-done.

**Review by aswaterman — APPROVED** [review]
LGTM, too.  Thanks @adurbin-rivos!

**Pull request merged**
