### PR TITLE
add support for mcountinhibit CSR

### PR DESCRIPTION
**Pull request by cyyself**
We hardwired mcountinihibit to 0 previously. Now, we implemented it.

### CODE REVIEW

**Review by aswaterman — CHANGES_REQUESTED** [review]
Please don't edit `encoding.h` directly, as this is an auto-generated file from https://github.com/riscv/riscv-opcodes

Note also when you update encoding.h over there, you should use `1U` rather than `1ULL` for these constants, which will minimize friction when using them in places where the underlying datatype is not `long long`.  After all, they are very small numbers.

Otherwise, the changes LGTM.

**Comment by cyyself** [comment]
> Please don't edit `encoding.h` directly, as this is an auto-generated file from https://github.com/riscv/riscv-opcodes
> 

Fixed.

> Note also when you update encoding.h over there, you should use `1U` rather than `1ULL` for these constants, which will minimize friction when using them in places where the underlying datatype is not `long long`. After all, they are very small numbers.
> 

Fixed. I checked the ISA spec. The mcounteren and mcountinhibit are 32-bit wide CSR, so using 1U is enough. 

> Otherwise, the changes LGTM.

Thanks!

**Review by aswaterman — APPROVED** [review]
LGTM now, thanks for the contribution.

**Comment by cyyself** [comment]
Is this PR ready to merge?

**Comment by aswaterman** [comment]
Yes, thanks for the ping.

**Pull request merged**
