### PR TITLE
Upgrade Spike to compile with c++2a and use designated initializers

### PR DESCRIPTION
**Pull request by rbuchner-aril**
See discussion here: https://github.com/riscv-software-src/riscv-isa-sim/pull/1560#discussion_r1447285791

This would clobber some of the changes made in [PR:1560](https://github.com/riscv-software-src/riscv-isa-sim/pull/1560) so I was waiting for that PR to merge before posting this. However, might make sense to merge this in before to allow some of the changes there to be cleaned up.

If you want to wait, I can rebase this branch onto master once 1560 is merged.

### CODE REVIEW

**Comment by scottj97** [comment]
@aswaterman any idea why the "Test debug" CI would fail its spike build when "Test Spike build" passed?

**Review by scottj97 — APPROVED** [review]
This nicely cleans up a lot of ugly.

**Comment by jerryz123** [comment]
I noticed the debug flow use `ubuntu-latest`, which is 22.04, while the Test flow uses `ubuntu-20.04`

**Comment by aswaterman** [comment]
@jerryz123 IMO we should not use `-latest` since inevitably we'll start getting failures when `-latest` increments.  I created a PR that attempts to roll the debug tests back to 20.04. https://github.com/riscv-software-src/riscv-isa-sim/pull/1584

**Comment by aswaterman** [comment]
#1584 is merged, so maybe this will pass after rebasing.

**Comment by rbuchner-aril** [comment]
Rebased onto PR 1584

**Comment by scottj97** [comment]
It would be good to understand why this failed on `ubuntu-latest` though, when other recent PRs have passed.

**Review by jerryz123 — APPROVED** [review]

**Pull request merged**
