### PR TITLE
Fix debug-mode regression introduced by 20e7f53

### PR DESCRIPTION
**Pull request by jerryz123**
Debug mode should break the processor out of wfi

### CODE REVIEW

**Comment by timsifive** [comment]
This change improves things from all tests failing to almost all tests failing. It's conceivable that #1177 caused these failures.
I'm going to dig into this more, but if you have time you should be able to run these tests by following the instructions at https://github.com/riscv-software-src/riscv-tests/tree/master/debug.

**Comment by timsifive** [comment]
Just tested some more, and #1177 is *not* the cause of these failures.

**Review by aswaterman — APPROVED** [review]

**Comment by aswaterman** [comment]
It's not clear from Tim's feedback whether or not I should merge this, but feel free to merge when you think it's appropriate @jerryz123

**Comment by jerryz123** [comment]
Still investigating.

**Comment by jerryz123** [comment]
@timsifive I believe this should work now.

The use of `wfi` in debug mode as a performance optimization threw me off. Those should be executed as nops.

**Comment by aswaterman** [comment]
Thanks, I’ll wait for Tim’s confirmation before merging.

**Review by scottj97 — APPROVED** [review]
I don't have any test coverage of this but the code looks clean and it doesn't seem to break anything else.

**Comment by aswaterman** [comment]
@jerryz123 / @timsifive please merge once this is deemed sufficient.

**Review by timsifive — APPROVED** [review]
This makes debug work again. Thanks!

**Pull request merged**
