### PR TITLE
rvp: Fixed rv32 legality issues.

### PR DESCRIPTION
**Pull request by marcfedorow**
You may check https://github.com/riscv/riscv-p-spec/issues/69 for clarification.

### CODE REVIEW

**Comment by marcfedorow** [comment]
Hi again, @hope51607, I kindly ask you to check this patch.

**Review by aswaterman — APPROVED** [review]
LGTM but will wait for @hope51607's ack (or a subsequent ping from @marcfedorow)

**Comment by marcfedorow** [comment]
Another small fix: required P-ext for SMAL insn.

**Comment by marcfedorow** [comment]
> LGTM but will wait for @hope51607's ack (or a subsequent ping from @marcfedorow)

@aswaterman, if you have no objection, I ask you to merge this PR.
Hopefully @hope51607 will take a look at it later.

**Comment by hope51607** [comment]
LGTM, Sorry for the late reply.

**Review by hope51607 — APPROVED** [review]

**Pull request merged**
