### PR TITLE
fix cmo support

### PR DESCRIPTION
**Pull request by liweiwei90**
This patchset will [use different cache block size for zicbom and zicboz operations and update the diasam for cbo.* instructions.

### CODE REVIEW

**Review by aswaterman — CHANGES_REQUESTED** [review]
These should be separate PRs.

The disassembler change looks fine.

I don't support the second change.  The RISC-V profiles are going to use a consistent cache-block size for the two extensions, so I doubt anyone will leverage the theoretical possibility that they might differ.  Just because someone can do something in RISC-V doesn't mean we need to model it in Spike.

**Comment by liweiwei90** [comment]
> 



> I don't support the second change. The RISC-V profiles are going to use a consistent cache-block size for the two extensions, so I doubt anyone will leverage the theoretical possibility that they might differ. Just because someone can do something in RISC-V doesn't mean we need to model it in Spike.

Sorry. I don't know how the RISC-V profiles are going to address this problem (@dkruckemyer-ventana). This is suggested in https://github.com/riscv-software-src/riscv-config/pull/79 by @pdonahue-ventana . And I remember this was also suggested in the QEMU PR for cmo support several month ago.

**Comment by aswaterman** [comment]
Paul’s not wrong, but it’s only a theoretical concern AFAICS. We can address it if it ever becomes relevant in practice.

Can you split the disassembler changes into a separate PR?

**Comment by pdonahue-ventana** [comment]
> Paul’s not wrong, but it’s only a theoretical concern AFAICS. We can address it if it ever becomes relevant in practice.

That's fine with me.  There are probably lots of other things that are theoretical concerns that we haven't even identified.  I just wanted to point this one out since I did happen to notice it.

**Comment by liweiwei90** [comment]
OK. I have sent a new PR(https://github.com/riscv-software-src/riscv-isa-sim/pull/1026) for it.

> Paul’s not wrong, but it’s only a theoretical concern AFAICS. We can address it if it ever becomes relevant in practice.
> 
> Can you split the disassembler changes into a separate PR?

**Comment by aswaterman** [comment]
Thanks.  I've merged #1026.

I'm going to close this for now.  In the unlikely event that realistic systems with divergent block sizes for Zicbom and Zicboz emerge, we can revisit the rest.

**Pull request closed without merging**
