### PR TITLE
make target_args() protected instead of private to allow subclasses to inject args

### PR DESCRIPTION
**Pull request by sagark**
see title

### CODE REVIEW

**Review by jerryz123 — APPROVED** [review]
LGTM, pending CI.

**Comment by scottj97** [comment]
I don't understand this. `target_args()` is not virtual, so a subclass couldn't override it. Even if it were virtual, subclasses in C++ can override private virtual methods.

What am I missing here?

**Comment by jerryz123** [comment]
We have a subclass which needs to append to targs in its own constructor.

**Comment by scottj97** [comment]
Sorry, I still don't get it...doesn't that mean that `targs` should be protected, not `target_args()`?

And why does this remove the `const` from the return type? Now the caller will be able to modify the private `targs`?

**Comment by jerryz123** [comment]
Yeah, we are modifying the private targs from the returned reference.

**Comment by scottj97** [comment]
I think it would be a lot clearer and safer to make `targs` protected instead. Leaving it private but modifying it from the child class is misleading.

**Comment by jerryz123** [comment]
Sure. I'll fix this now.

**Comment by jerryz123** [comment]
Actually I think I have another approach that bypasses the need to modify the targs member entirely... its a bit more invasive of a change

**Pull request merged**
