### PR TITLE
Refactor put_csr to direct write

### PR DESCRIPTION
**Pull request by demin-han**
1. put_csr needs search
2. MSTATUS_MPV not written back for RV32

### CODE REVIEW

**Review by scottj97 — CHANGES_REQUESTED** [review]
I agree this is an improvement -- no reason to require a lookup into `csrmap` -- but I don't understand the part about "MSTATUS_MPV not written back for RV32".

Is there a bug that this fixes? If so we need a lot more explanation of the case.

I can't see how this change would affect MPV on RV32, but maybe I'm missing something.

**Comment by demin-han** [comment]
@scottj97 
MPV located in mstatush when RV32. 

if (xlen == 32) {
    csrmap[CSR_MSTATUS] = std::make_shared<rv32_low_csr_t>(proc, CSR_MSTATUS, mstatus);
    csrmap[CSR_MSTATUSH] = mstatush = std::make_shared<rv32_high_csr_t>(proc, CSR_MSTATUSH, mstatus);
  } else {
    csrmap[CSR_MSTATUS] = mstatus;
  }

CSR_MSTUTUS is associated with lower part of mstatus when RV32.
so put_csr(CSR_MSTATUS, s) only update lower part of mstatus, MPV in mstatush not updated.

**Review by scottj97 — APPROVED** [review]
Yes. I see the problem now.

I think RV32 Hypervisor has seen very limited usage (or none at all) because I suspect this has been broken all along, since MPV was first added.

I've confirmed that this PR doesn't change any RV64 Hypervisor behavior, but I don't have any test coverage of RV32 Hypervisor.

**Review by aswaterman — APPROVED** [review]
Ah, that's subtle.

**Pull request merged**
