### PR TITLE
vcpop.m, vfirst.m: delete unnecessary VSTART write.

### PR DESCRIPTION
**Pull request by h-cheng**
For vector mask intructions like vcpop.m, vfirst.m, vmsbf.m, vmsif.m, vmsof.m, viota.m, VSTART should be zero and it is checked in Spike. So it is optional to reset VSTART at the end of these instructions.
However, there is kind of inconsistency in Spike that VSTART is reset for vcpop.m and vfirst.m, but not for vmsbf.m, vmsif.m, vmsof.m, viota.m. I would suggest doing the same thing for them as well.
One additional benefit for this change is making the commit logs of all vector instructions contain a "c8_vstart" segment, which is easy to parse during verification.

### CODE REVIEW

**Review by aswaterman — COMMENTED** [review]
> So it is optional to reset VSTART at the end of these instructions.

For this reason, the extra code to reset vstart to 0 strikes me as unnecessary clutter.

> However, there is kind of inconsistency in Spike that VSTART is reset for vcpop.m and vfirst.m

I agree this is inconsistent, but it would seem cleaner to resolve it in the opposite manner, by deleting the explicit `vstart` write from `vcpop.m` and `vfirst.m`.

**Comment by h-cheng** [comment]
Sounds good. I submitted a new commit here that deletes `vstart` from `vcpop.m` and `vfirst.m`.

**Comment by scottj97** [comment]
Please update the title of the PR to match the new implementation, and squash the two commits together. No need to add code in one commit and then immediately remove it in the next commit.

**Comment by h-cheng** [comment]
Sorry. I mistakenly touched previous two existing commits when I squash mine. I will close this PR and submit a clean one later.

**Pull request closed without merging**
