### PR TITLE
Fix vsstatus.FS misbehavior

### PR DESCRIPTION
**Pull request by scottj97**
See #660. This implements the suggested fix.

### CODE REVIEW

**Comment by aswaterman** [comment]
LGTM, but I'll wait for @avpatel's signoff.

**Comment by avpatel** [comment]
Looks good to me. @aswaterman please take this PR

**Comment by scottj97** [comment]
Why squash? I deliberately separated out refactorings from the functional change for the bugfix. Squashing them together makes future code archaeology more difficult...

**Comment by aswaterman** [comment]
Yes, I should've merged this one.  Oh well.

**Pull request merged**
